.gitignore, docs/source/api.rst, docs/source/conf.py, docs/source/index.rst, torchquantum/functional.py
* improve git ignore
* modify docs/source/api.rst, docs/source/index.rst to include primary modules
* modify docs/source/conf.py to add theme, support google styled docstring, view code extension, include module
=> modify doc conf to init docstring publish task

torchquantum/measure.py
Fix the bug that measure will cause runtime error when n_wires=1.
=> [major] fix bugs in torchquantum/measure.py

.flake8, .github/CODEOWNERS, .github/workflows/lint.yaml, .github/workflows/pull_request.yaml, .pre-commit-config.yaml, README.md, setup.py, torchquantum/__version__.py
Hello 👋 
This small PR adds new GH CI workflows, flake8 configuration to the torchquantum project to ensure Python style consistency, prevents codebase from common mistakes.
=> (feat/github-ci) ensure python style consistency, add pre-commit hooks

README.md
Quick edit to make the logo on the README visible by changing it to a relative path.
=> Fix Logo on README

examples/quantum_transformer/Qtransformer-torch.ipynb
=> Fix typo in Qtransformer-torch.ipynb

setup.py
=> [minor] fix the qiskit version to make sure interfact

README.md, examples/qaoa/max_cut_backprop_new.py, examples/simple_mnist/mnist_example_no_binding_new.py, torchquantum/devices.py, torchquantum/encoding.py, torchquantum/functional.py, torchquantum/measurement.py, torchquantum/plugins/qiskit_plugin.py
conversions to qiskit, qasm are done by op_history in qdev
=> Feat op history, and example modifications

torchquantum/measurement.py
joint exp val
conjugate transpose should be applied on the left state
=> [major] fixed critical bug on the measurement

torchquantum/vqe_utils.py
Do we need to keep the debugging tools?
=> removes debugging from vqe_utils.py

examples/simple_mnist/README.md
Updated the mnist example README to have the correct filename to run the example.
=> Updated file name of simple_mnist example

torchquantum/densityfunc.py, torchquantum/devices.py, torchquantum/encoding.py, torchquantum/functional.py, torchquantum/graph.py, torchquantum/layers.py, torchquantum/noise_model.py, torchquantum/pulse_utils.py, torchquantum/super_utils.py, torchquantum/utils.py, torchquantum/vqe_utils.py
=> issue #135 @Hanuri-Wang docstring added to the function which lack documentation

examples/index.rst, examples/superdense_coding/README.md, examples/superdense_coding/superdense_coding_torchquantum.ipynb, examples/superdense_coding/superdense_coding_torchquantum.py
As per issue #136. I've implemented the superdense coding algorithm. I made a new folder in the examples folder and placed the .ipynb and .py files inside. I've also uploaded it to the toctree, so that the static jupyter notebook tutorial appears in the torchquantum docs.
=> Adding Superdense Coding 

torchquantum/utils.py
#133 i made a function to calculate the gradient of a given model, it returns a tensor of the gradients using the parameter shift rule as a part of the unitaryhack, added  to `utils.py`
=> Adding parameter shift gradient as a fucntion

setup.py
PR addressing https://github.com/mit-han-lab/torchquantum/issues/161.
For reviewers: feel free to update `torchdiffeq` to an older version.
=> Add Missing Dependency

examples/qubit_rotation/README.md, examples/qubit_rotation/TQ_Qubit_Rotation_Tutorial.ipynb, examples/qubit_rotation/qubit_rotation.py
Example of qubit rotation optimization (based on Pennylane's qubit rotation tutorial) in TorchQuantum.
=> Qubit Rotation Example

requirements.txt, setup.py
Edited `setup.py` to read in requirements from `requirements.txt`.
There were some packages hardcoded within `setup.py` - I have added/updated those within `requirements.txt`.
=> Basic usage fix

torchquantum/algorithm/__init__.py, torchquantum/algorithm/qft.py, torchquantum/layer/layers.py
Creates a QFT Layer with both the normal and inverse QFT circuits
=> QFT Layer and Algorithm

torchquantum/layer/__init__.py, torchquantum/layer/layers.py, torchquantum/layer/nlocal.py
Support for NLocal circuit purely in TorchQuantum using the layer interface
=> NLocal Circuits

README.md
Updated paths and fixed deadlinks for the examples (vqe and mnist)
=> Minor Update to README

examples/index.rst
Added the Qubit Rotation Notebook to the index.rst of docs.
=> [minor] Add Qubit Rotation Tutorial to Docs

examples/superdense_coding/superdense_coding_torchquantum.ipynb
Minor update to tutorials to be better compatible with the documentation website.
=> Minor Documentation Updates

torchquantum/datasets/vowel.py, torchquantum/optimization.py, torchquantum/super_layers.py
Enhancing documentation - resolving part of the issue #135.
=> Added Docstrings (see issue #135)

.github/workflows/functional_tests.yaml, requirements.txt, torchquantum/util/utils.py
For the upcoming deadline, I’m keeping qiskit < 1.0.0 but have been working on refactoring the completely deprecated IBMQ aspect.
=> Adapting TQ with New Qiskit Deprecations

README.md, examples/ICCAD22_tutorial/README.md, setup.py
this will add texts to the pypi page through the usage of the README file to populate your pypi package page.
I also noticed some links that needed some updating so I did that too.
Do not hesitate to reach out if you have any queries.
Kind Regards,
Hafedh Hichri
=> Improvements
