- setup.py
> add a new line to setup.py

- torchquantum/measurement.py
There is a bug in tq.measure().
The measurement probability equals the square of the |magnitude|
> fixed a bug in tq.measure()

- examples/quantumnat/quantumnat.py
Hi Hanrui,
In the forward function, need to reset_states(bsz) for self.q_device. If not, the program will run into the following error:
```
RuntimeError: Expected size for first two dimensions of batch2 tensor to be: [256, 2] but got: [1, 2]
```
Thanks,
Caitao
> fix a minor bug in quantumnat.py

- torchquantum/algorithms/hamiltonian.py
- torchquantum/algorithms/vqe.py
- torchquantum/datasets/layer_regression.py
- torchquantum/datasets/vqe.py
- torchquantum/density.py
- torchquantum/densityfunc.py
- torchquantum/measurement.py
- torchquantum/module.py
- torchquantum/node.py
- torchquantum/plugins/qiskit_pulse.py
- torchquantum/prune_utils.py
- torchquantum/pulse.py
- torchquantum/quantization/clifford_quantization.py
Enhancing documentation - resolving part of the issue #135
> Added Docstrings (see issue #135)

- test/operators/test_op.py
- torchquantum/functional.py
- torchquantum/operators.py
Hello, @Hanrui-Wang. I added a sample PR to the codebase by adding the SDG gate. I intend to add more, but first I'd like you to check if I did everything right. As described in Issue #134, I put the sdg matrix to the matrix dictionary in functional.py and wrote a function for the gate. Next, I added the sdg class to the operators.py file, and finally, I added the sdg gate to the test_op.py file.
> PR for Issue #134 Unitary Hack

- test/operators/test_op.py
- torchquantum/functional.py
- torchquantum/operators.py
Link to : add supports for more basic operations and layers #134 and #136
Changes I made:
Add QFT function and QFT_matrix function in functional.py
Add QFT class in operators.py
Add test for QFT in test_op.py
> Add QFT operation

- examples/grover/README.md
- examples/grover/grover_example_sudoku.py
- torchquantum/algorithms/__init__.py
- torchquantum/algorithms/grover.py
Added support for Grover's search algorithm. 
Implemented the Grover's search algorithm in `torchquantum.algoirithms`. Added example code to solve 2x2 sudoku using the same in the `examples` directory. Resolves #136.
> Implementation of Grover's search algorithm

- torchquantum/plugin/qiskit/qiskit_plugin.py
I saw after the directory restructuring that some of my code was failing when trying to output the circuit qasm. This was caused by the line in `qiskit_plugins.py` which attempts to import as: `from torchquantum.plugin.qiskit_unitary_gate import UnitaryGate`
I checked the `__init__.py` files and it looked like this import should be okay, but for some reason it was still failing to find the `qiskit_unitary_gate` module. I made a simple fix which was just to include the `qiskit` directory in the import statement, but I'm still not sure why the `__init__.py` was failing to find it in the first place.
But hopefully this fix will work for now.
> Update module path to qiskit_unitary_gate

- docs/source/api_layers.rst
- docs/source/api_operators.rst
- docs/source/index.rst
- Adding a category for the layers
- Updating the operators path (so it actually displays the functions)
> Updating the Documentation

- README.md
- torchquantum/plugin/qiskit/qiskit_plugin.py
Fixes bug with importing transpiled circuits which are mapped trivially (resulting in a set initial_layout but a null final_layout). This will come up often on circuits that are transpiled with optimization_level=0, though this can happen on any level of optimization if the trivial layout happens to be optimal.
Code to replicate the bug:
`
from torchquantum.plugins import qiskit2tq
from qiskit.circuit.library import RealAmplitudes
from qiskit.compiler import transpile
from qiskit.providers.fake_provider import FakeGuadalupe
backend = FakeGuadalupe()
ansatz = RealAmplitudes(2, reps=1)
ansatz = transpile(ansatz, backend, optimization_level=0)
params = [0]*len(ansatz.parameters)
ansatz = ansatz.bind_parameters(params)
tq_layer = qiskit2tq(ansatz)
`
> Bugfix: Error when uploading some circuits to TorchQuantum

- examples/gradient_pruning/q_models.py
- torchquantum/pulse/utils.py
`torch.range` and `torch.outer` are deprecated and will be removed in a future PyTorch release.
Fixed with TorchFix https://github.com/pytorch/test-infra/tree/main/tools/torchfix
> Update deprecated `torch.range` and `torch.outer`

- torchquantum/layer/layers.py
- torchquantum/plugin/qiskit/qiskit_unitary_gate.py
As discussed, added support for four entanglement types: EntangleFull, EntangleLinear, EntangleCircular, and EntanglePairwise. This is broken into two commits: the first adds the updates changes (would recommend focusing review there) and the second fixes the style of the layers.py file.
> Adding Entangle Layers

- test/layers/test_rotgate.py
- torchquantum/layer/__init__.py
- torchquantum/layer/general.py
Adding support for the GlobalR/RX/RY General Gates as layers, similar to the [GlobalR Gates](https://qiskit.org/documentation/_modules/qiskit/circuit/library/generalized_gates/gr.html) from Qiskit
> GlobalR/GlobalRX/GlobalRY Gates

- README.md
For some reason, add the extra space auto-rendered it as code for the README so this is a minor update to get the tags back to properly formatted.
> Minor README Update

- .github/workflows/functional_tests.yaml
- docs/requirements.txt
- docs/source/conf.py
- readthedocs.yaml
- requirements.txt
- torchquantum/util/utils.py
Adding just the docs updates from #231 without the density matrix base.
> Same Docs Updates as #231 without DM

- requirements.txt
Updated the qiskit runtime to be compatible with our stack (namely, qiskit<1.0.0).
> Bugfix: Add qiskit runtime dependency

- torchquantum/operator/standard_gates/__init__.py
**Error** 
```
tq.H()
```
Claims that H is not found on tq.
**Problem**
Essentially, the trick we used for using __class__ for an alias results in the original name. 
**Proposed Solution**
Therefore, I just decided to remove the __all__ from this so the aliases are automatically exported. In addition, to ensure the other variables are not exported, I prefixed them in _. This addresses one of the bugs in the Slack.
> Bugfix for the H not found on tq

- README.md
- requirements.txt
- torchquantum/measurement/measurements.py
Not sure whether I am misunderstanding the function.
self.measure_multiple_times returns a [len(obs_list), num_wires] tensor, you have to take the product over the wires first to get the measurement of the Pauli string and then sum over the obs_list (multiplied by coefficients in the case of MeasureMultiQubitPaulisum.
> Fix MeasureMulti*PauliSum

- test/encoding/test_encodings.py
- torchquantum/encoding/encodings.py
This PR adds the ability to fix parameters of some parameterised gates in a `GeneralEncoder`.
This allows, for example, a single parameterised gate to have a fixed parameter, shared across all items in the batch, while all other parameters can be dynamically provided. The change is fully backwards compatible, and no changes need to be made to existing encoder definitions.
This supports ansatze which have some fixed gates which aren't Paulis or other named operators.
I expect this could already be achieved by subclassing existing operators, but I think this imposes less effort on the user.
Opening this to gauge interest. Shall update documentation and tests pending feedback.
```
>>> import torchquantum as tq
>>> import torch
>>> 
>>> 
>>> enc1 = [{'input_idx': [0], 'func': 'rx', 'wires': …
```
> Allow fixed parameters in GeneralEncoder

- examples/clifford_qnn/mnist_clifford_qnn.py
- torchquantum/operator/op_types.py
To fix issue mit-han-lab/torchquantum#213, it looks like the ```QuantumDevice``` needs to be initialized with the batch size (batch size is 1 by default which is why the size was [1, 2] instead of [256, 2]). 
After this change, there is a ```NameError``` for ```CliffordQuantizer```:
which can be fixed by importing it in the ```torchquantum/operator/op_types.py``` file, which calls the ```CliffordQuantizer``` function.
After these changes, I believe ```examples/clifford_qnn/mnist_clifford_qnn.py``` can run out-of-the-box:
@Hanrui-Wang @01110011011101010110010001101111
> Fix for issue #213
